{{- $apiRouteEnabled := and .Values.gateway.enabled (gt (len .Values.api.hostnames) 0) }}
{{- $webRouteEnabled := and .Values.gateway.enabled .Values.web.enabled (gt (len .Values.web.hostnames) 0) }}
{{- if $apiRouteEnabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "app.api.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
  hostnames:
    {{- range .Values.api.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /fhir
      backendRefs:
        - name: {{ include "app.api.fullname" . }}
          port: 8080
{{- end }}
{{- if and $apiRouteEnabled $webRouteEnabled }}
---
{{- end }}
{{- if $webRouteEnabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "app.web.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
  hostnames:
    {{- range .Values.web.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "app.web.fullname" . }}
          port: 3000
{{- end }}
